/**
 * P2.1 — Domain Models (src/core/models.js)
 *
 * Modelos normalizados do StreamGrab: MediaInfo, Format e DownloadJob,
 * com os estados do ciclo de vida do job. Sem logica de download.
 *
 * Contratos:
 *  - Format: shape normalizado espelhando os formatos dos adapters existentes
 *    (ytdlp/youtube: formatId, url, container, codecs, qualityLabel, bitrate,
 *    width, height, fps, hasVideo, hasAudio, contentLength).
 *  - MediaInfo: shape da analise (title, durationSeconds, sourceType, provider,
 *    formats, variants, progressiveFormats, adaptiveVideoFormats, adaptiveAudioFormats).
 *  - DownloadJob: ciclo de vida queued -> analyzing -> preparing -> downloading
 *    -> (paused | merging) -> completed/failed/cancelled, com historico de
 *    transicoes e serializacao limpa (sem campos circulares).
 */

// ---------------------------------------------------------------------------
// Estados do job (architect.md secao 10)
// ---------------------------------------------------------------------------

export const JOB_STATES = Object.freeze([
  'queued',
  'analyzing',
  'preparing',
  'downloading',
  'paused',
  'merging',
  'completed',
  'failed',
  'cancelled',
]);

export const TERMINAL_JOB_STATES = Object.freeze(['completed', 'failed', 'cancelled']);

export const CHECKPOINT_TASK_STATES = Object.freeze([
  'pending',
  'downloading',
  'downloaded',
  'processing',
  'completed',
]);

/** Transicoes validas de cada estado (architect.md secoes 10 e 24). */
export const JOB_TRANSITIONS = Object.freeze({
  queued: Object.freeze(['analyzing', 'cancelled']),
  analyzing: Object.freeze(['preparing', 'failed', 'cancelled']),
  preparing: Object.freeze(['downloading', 'failed', 'cancelled']),
  downloading: Object.freeze(['paused', 'merging', 'completed', 'failed', 'cancelled']),
  paused: Object.freeze(['downloading', 'cancelled']),
  merging: Object.freeze(['completed', 'failed']),
  completed: Object.freeze([]),
  failed: Object.freeze([]),
  cancelled: Object.freeze([]),
});

export function isValidJobState(state) {
  return typeof state === 'string' && JOB_STATES.includes(state);
}

export function isTerminalJobState(state) {
  return TERMINAL_JOB_STATES.includes(state);
}

export function isValidCheckpointTaskState(state) {
  return typeof state === 'string' && CHECKPOINT_TASK_STATES.includes(state);
}

export function canTransition(from, to) {
  return isValidJobState(from) && isValidJobState(to) && JOB_TRANSITIONS[from].includes(to);
}

// ---------------------------------------------------------------------------
// Format
// ---------------------------------------------------------------------------

/**
 * Cria um Format normalizado. Entrada aceita tanto o shape dos adapters
 * (formatId/url/container/codecs/qualityLabel/...) quanto um objeto parcial —
 * campos ausentes viram valores neutros, sem lancar.
 *
 * @param {object} [input]
 * @param {string} [input.formatId]
 * @param {string} [input.url]
 * @param {string} [input.container]
 * @param {string} [input.codecs]
 * @param {string} [input.qualityLabel]
 * @param {number} [input.bitrate]
 * @param {number} [input.width]
 * @param {number} [input.height]
 * @param {number} [input.fps]
 * @param {boolean} [input.hasVideo]
 * @param {boolean} [input.hasAudio]
 * @param {number} [input.contentLength]
 * @param {string} [input.language] — P12: ISO 639-1 code (e.g. 'pt', 'en')
 * @param {string} [input.label] — P12: human-readable name (e.g. 'Portuguese')
 * @param {boolean} [input.isDefault] — P12: default track
 * @param {boolean} [input.isAutoGenerated] — P12: ASR auto-generated subtitle
 * @returns {{ formatId: string, url: string, container: string, codecs: string, qualityLabel: string, bitrate: number, width: number, height: number, fps: number, hasVideo: boolean, hasAudio: boolean, contentLength: number, language: string, label: string, isDefault: boolean, isAutoGenerated: boolean }}
 */
export function createFormat(input = {}) {
  if (input === null || typeof input !== 'object') {
    throw new TypeError('createFormat: entrada deve ser um objeto');
  }
  return {
    formatId: String(input.formatId || input.id || ''),
    url: String(input.url || ''),
    container: String(input.container || input.ext || ''),
    codecs: String(input.codecs || ''),
    qualityLabel: String(input.qualityLabel || input.resolution || ''),
    bitrate: Number(input.bitrate || input.bandwidth || 0) || 0,
    width: Number(input.width) || 0,
    height: Number(input.height) || 0,
    fps: Number(input.fps) || 0,
    hasVideo: Boolean(input.hasVideo ?? (input.vcodec && input.vcodec !== 'none')),
    hasAudio: Boolean(input.hasAudio ?? (input.acodec && input.acodec !== 'none')),
    contentLength: Number(input.contentLength || input.filesize || input.estimatedSize || 0) || 0,
    // P12: audio track + subtitle fields
    language: String(input.language || ''),
    label: String(input.label || ''),
    isDefault: Boolean(input.isDefault),
    isAutoGenerated: Boolean(input.isAutoGenerated),
  };
}

/** Valida o shape de um Format ja normalizado (ou parcial). */
export function isValidFormat(format) {
  return (
    format !== null &&
    typeof format === 'object' &&
    typeof format.formatId === 'string' &&
    typeof format.url === 'string' &&
    typeof format.bitrate === 'number' &&
    typeof format.hasVideo === 'boolean' &&
    typeof format.hasAudio === 'boolean'
  );
}

// ---------------------------------------------------------------------------
// P12: AudioTrack + SubtitleTrack
// ---------------------------------------------------------------------------

/**
 * Cria um AudioTrack normalizado — representa uma faixa de áudio distinta
 * (idioma + qualidade). Uma faixa pode ter múltiplos formatos.
 *
 * @param {object} [input]
 * @param {string} [input.language] — ISO 639-1 code (e.g. 'pt', 'en', 'und')
 * @param {string} [input.label] — human-readable name (e.g. 'Portuguese')
 * @param {boolean} [input.isDefault] — default track for this language
 * @param {Array<object>} [input.formats] — Format[] sorted by bitrate desc
 * @returns {{ language: string, label: string, isDefault: boolean, formats: Array }}
 */
export function createAudioTrack(input = {}) {
  return {
    language: String(input.language || 'und'),
    label: String(input.label || ''),
    isDefault: Boolean(input.isDefault),
    formats: Array.isArray(input.formats) ? input.formats : [],
  };
}

/**
 * Cria um SubtitleTrack normalizado — representa uma pista de legenda.
 *
 * @param {object} [input]
 * @param {string} [input.language] — ISO 639-1 code
 * @param {string} [input.label] — human-readable name
 * @param {boolean} [input.isAutoGenerated] — ASR auto-generated
 * @param {boolean} [input.isDefault] — default subtitle track
 * @param {object} [input.format] — { ext: 'vtt', url: '...' }
 * @returns {{ language: string, label: string, isAutoGenerated: boolean, isDefault: boolean, format: object|null }}
 */
export function createSubtitleTrack(input = {}) {
  return {
    language: String(input.language || 'und'),
    label: String(input.label || ''),
    isAutoGenerated: Boolean(input.isAutoGenerated),
    isDefault: Boolean(input.isDefault),
    format: input.format || null,
  };
}

// ---------------------------------------------------------------------------
// MediaInfo
// ---------------------------------------------------------------------------

/**
 * Cria um MediaInfo normalizado a partir da analise de um adapter.
 * `formats` e opcional: quando ausente, e derivado de variants quando possivel.
 */
export function createMediaInfo(input = {}) {
  if (input === null || typeof input !== 'object') {
    throw new TypeError('createMediaInfo: entrada deve ser um objeto');
  }

  const rawFormats = Array.isArray(input.formats) ? input.formats : [];
  const progressiveFormats = Array.isArray(input.progressiveFormats)
    ? input.progressiveFormats.map((f) => createFormat(f))
    : [];
  const adaptiveVideoFormats = Array.isArray(input.adaptiveVideoFormats)
    ? input.adaptiveVideoFormats.map((f) => createFormat(f))
    : [];
  const adaptiveAudioFormats = Array.isArray(input.adaptiveAudioFormats)
    ? input.adaptiveAudioFormats.map((f) => createFormat(f))
    : [];
  const variants = Array.isArray(input.variants) ? input.variants : [];

  const formats = rawFormats.length
    ? rawFormats.map((f) => createFormat(f))
    : [...progressiveFormats, ...adaptiveVideoFormats, ...adaptiveAudioFormats];

  return {
    kind: String(input.kind || 'unknown'),
    sourceType: String(input.sourceType || input.kind || 'unknown'),
    provider: String(input.provider || ''),
    title: String(input.title || 'Video'),
    pageUrl: String(input.pageUrl || ''),
    videoId: String(input.videoId || ''),
    durationSeconds: Number(input.durationSeconds || input.duration || 0) || 0,
    formats,
    progressiveFormats,
    adaptiveVideoFormats,
    adaptiveAudioFormats,
    variants,
    // P12: audio tracks + subtitles
    audioTracks: Array.isArray(input.audioTracks) ? input.audioTracks : [],
    subtitleTracks: Array.isArray(input.subtitleTracks) ? input.subtitleTracks : [],
  };
}

/** Valida o shape de um MediaInfo. */
export function isValidMediaInfo(info) {
  return (
    info !== null &&
    typeof info === 'object' &&
    typeof info.title === 'string' &&
    typeof info.sourceType === 'string' &&
    Array.isArray(info.formats) &&
    Array.isArray(info.variants)
  );
}

// ---------------------------------------------------------------------------
// DownloadJob
// ---------------------------------------------------------------------------

let jobSequence = 0;

function nowIso() {
  return new Date().toISOString();
}

function cloneSerializableObject(input) {
  if (input === null || typeof input !== 'object' || Array.isArray(input)) {
    return {};
  }
  return JSON.parse(JSON.stringify(input));
}

function normalizeSegmentCheckpointEntry(entry = {}) {
  const stream = String(entry.stream || entry.track || 'video');
  const index = Number(entry.index);
  return {
    id: String(
      entry.id ||
        createSegmentTaskId({
          stream,
          representationId: entry.representationId,
          segmentIndex: Number.isFinite(index) ? index : 0,
          init: Boolean(entry.init),
        })
    ),
    stream,
    representationId: String(entry.representationId || ''),
    index: Number.isFinite(index) ? index : 0,
    init: Boolean(entry.init),
    url: String(entry.url || ''),
    status: String(entry.status || 'pending'),
  };
}

function createDefaultCheckpoint() {
  return {
    version: 1,
    backend: '',
    manifestUrl: '',
    outputMode: 'single',
    taskState: 'pending',
    selected: {
      videoRepresentationId: '',
      audioRepresentationId: '',
    },
    segments: [],
    completedSegmentIds: [],
    diagnostics: {},
    updatedAt: nowIso(),
  };
}

/**
 * Gera um ID de job unico, resistente a colisao apos crash recovery.
 * Formato: job-<timestamp>-<random> — nunca colide com IDs restaurados
 * de storage (que usam o formato legado "job-<n>").
 */
function generateJobId() {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 8);
  return `job-${ts}-${rand}`;
}

export function createSegmentTaskId({
  stream = 'video',
  representationId = '',
  segmentIndex = 0,
  init = false,
} = {}) {
  const normalizedStream = String(stream || 'video').trim().toLowerCase() || 'video';
  const normalizedRepresentation = String(representationId || '').trim() || 'default';
  const normalizedIndex = Number.isFinite(Number(segmentIndex)) ? Number(segmentIndex) : 0;
  const kind = init ? 'init' : 'seg';
  return `${normalizedStream}:${normalizedRepresentation}:${kind}:${normalizedIndex}`;
}

export function createSegmentCheckpoint(input = {}) {
  const base = createDefaultCheckpoint();
  const taskState = String(input.taskState || base.taskState);
  const segments = Array.isArray(input.segments)
    ? input.segments.map((entry) => normalizeSegmentCheckpointEntry(entry))
    : base.segments;
  const completedSegmentIds = Array.isArray(input.completedSegmentIds)
    ? [...new Set(input.completedSegmentIds.map((value) => String(value || '')).filter(Boolean))]
    : base.completedSegmentIds;

  return {
    version: Number(input.version || base.version) || 1,
    backend: String(input.backend || base.backend),
    manifestUrl: String(input.manifestUrl || base.manifestUrl),
    outputMode: String(input.outputMode || base.outputMode),
    taskState: isValidCheckpointTaskState(taskState) ? taskState : base.taskState,
    selected: {
      videoRepresentationId: String(
        input.selected?.videoRepresentationId || input.selectedVideoRepresentationId || ''
      ),
      audioRepresentationId: String(
        input.selected?.audioRepresentationId || input.selectedAudioRepresentationId || ''
      ),
    },
    segments,
    completedSegmentIds,
    diagnostics: cloneSerializableObject(input.diagnostics),
    updatedAt: nowIso(),
  };
}

export function getJobCheckpoint(job) {
  if (!job?.meta?.checkpoint) return null;
  return createSegmentCheckpoint(job.meta.checkpoint);
}

export function setJobCheckpoint(job, checkpoint) {
  if (!job || typeof job !== 'object') {
    throw new TypeError('setJobCheckpoint: job deve ser um objeto');
  }
  const nextCheckpoint = createSegmentCheckpoint(checkpoint);
  job.meta = {
    ...(job.meta || {}),
    checkpoint: nextCheckpoint,
    taskState: nextCheckpoint.taskState,
    taskStateUpdatedAt: nextCheckpoint.updatedAt,
  };
  return nextCheckpoint;
}

export function setJobTaskState(job, taskState, { checkpoint = null } = {}) {
  if (!job || typeof job !== 'object') {
    throw new TypeError('setJobTaskState: job deve ser um objeto');
  }
  if (!isValidCheckpointTaskState(taskState)) {
    const err = new Error(`Estado de checkpoint invalido: "${taskState}"`);
    err.code = 'INVALID_CHECKPOINT_TASK_STATE';
    throw err;
  }
  const updatedAt = nowIso();
  job.meta = {
    ...(job.meta || {}),
    taskState,
    taskStateUpdatedAt: updatedAt,
  };
  if (checkpoint) {
    const nextCheckpoint = createSegmentCheckpoint({
      ...checkpoint,
      taskState,
    });
    nextCheckpoint.updatedAt = updatedAt;
    job.meta.checkpoint = nextCheckpoint;
  } else if (job.meta.checkpoint) {
    job.meta.checkpoint = {
      ...job.meta.checkpoint,
      taskState,
      updatedAt,
    };
  }
  return job;
}

/**
 * Cria um DownloadJob com estado inicial `queued`.
 *
 * Opcoes:
 *  - id: identificador (default: "job-<ts>-<rand>" unico)
 *  - url: URL de origem (obrigatoria)
 *  - title: titulo opcional (preenchido na analise)
 *  - meta: mapa extra serializavel (opcional)
 *
 * @param {object} [opts]
 * @param {string} [opts.id]
 * @param {string} opts.url
 * @param {string} [opts.title]
 * @param {object} [opts.meta]
 * @returns {{ id: string, url: string, title: string, state: string, error: null, meta: object, createdAt: string, updatedAt: string, history: Array }}
 */
export function createDownloadJob({ id, url, title = '', meta = {} } = {}) {
  if (!url || typeof url !== 'string') {
    throw new TypeError('createDownloadJob: url e obrigatoria');
  }
  if (meta === null || typeof meta !== 'object') {
    throw new TypeError('createDownloadJob: meta deve ser um objeto');
  }
  jobSequence += 1;
  const now = nowIso();
  return {
    id: String(id || generateJobId()),
    url,
    title: String(title || ''),
    state: 'queued',
    error: null,
    meta: {
      ...meta,
      taskState: isValidCheckpointTaskState(meta.taskState) ? meta.taskState : 'pending',
      taskStateUpdatedAt: String(meta.taskStateUpdatedAt || now),
      checkpoint: meta.checkpoint ? createSegmentCheckpoint(meta.checkpoint) : undefined,
    },
    createdAt: now,
    updatedAt: now,
    history: [{ from: null, to: 'queued', at: now }],
  };
}

/**
 * Transiciona o job para `nextState`, validando contra JOB_TRANSITIONS.
 * Lanca Error com code 'INVALID_JOB_TRANSITION' se a transicao for invalida.
 * `error` (opcional) e gravado apenas em estados de falha/terminal.
 */
export function transitionJob(job, nextState, { error = null } = {}) {
  if (!isValidJobState(nextState)) {
    const err = new Error(`Estado invalido: "${nextState}"`);
    err.code = 'INVALID_JOB_STATE';
    throw err;
  }
  if (!canTransition(job.state, nextState)) {
    const err = new Error(`Transicao invalida: ${job.state} -> ${nextState}`);
    err.code = 'INVALID_JOB_TRANSITION';
    throw err;
  }
  const now = nowIso();
  job.state = nextState;
  job.updatedAt = now;
  job.error = error ? serializeError(error) : null;
  job.history.push({ from: job.history.at(-1).to, to: nextState, at: now });
  return job;
}

function serializeError(err) {
  if (err === null || typeof err !== 'object') return String(err);
  return {
    message: String(err.message || String(err)),
    code: err.code || '',
    needsAuth: Boolean(err.needsAuth),
    status: err.status || 0,
  };
}

/** Serializa o job sem campos circulares (metodos, referencias). */
export function serializeJob(job) {
  return {
    id: job.id,
    url: job.url,
    title: job.title,
    state: job.state,
    error: job.error,
    meta: { ...job.meta },
    createdAt: job.createdAt,
    updatedAt: job.updatedAt,
    history: job.history.map((entry) => ({ ...entry })),
  };
}

export function toJson(job) {
  return serializeJob(job);
}

// ---------------------------------------------------------------------------
// Helpers de conveniencia (shape "antigo" -> modelo)
// ---------------------------------------------------------------------------

/**
 * Converte uma variant HLS/master (shape: uri, resolution, width, height,
 * bandwidth, codecs) em um Format normalizado.
 */
export function formatFromVariant(variant = {}) {
  return createFormat({
    formatId: '',
    url: String(variant.uri || ''),
    container: '',
    codecs: String(variant.codecs || ''),
    qualityLabel: String(variant.resolution || ''),
    bitrate: Number(variant.bandwidth || 0) || 0,
    width: Number(variant.width) || 0,
    height: Number(variant.height) || 0,
    hasVideo: true,
    hasAudio: true,
  });
}
