// ---------------------------------------------------------------------------
// Format model — normalized video/audio format representation.
// ---------------------------------------------------------------------------

/**
 * Cria um Format normalizado. Entrada aceita tanto o shape dos adapters
 * (formatId/url/container/codecs/qualityLabel/...) quanto um objeto parcial —
 * campos ausentes viram valores neutros, sem lancar.
 *
 * @param {object} [input]
 * @param {string} [input.formatId]
 * @param {string} [input.url]
 * @param {string} [input.container]
 * @param {string} [input.codecs]
 * @param {string} [input.qualityLabel]
 * @param {number} [input.bitrate]
 * @param {number} [input.width]
 * @param {number} [input.height]
 * @param {number} [input.fps]
 * @param {boolean} [input.hasVideo]
 * @param {boolean} [input.hasAudio]
 * @param {number} [input.contentLength]
 * @param {string} [input.language]
 * @param {string} [input.label]
 * @param {boolean} [input.isDefault]
 * @param {boolean} [input.isAutoGenerated]
 */
export function createFormat(input = {}) {
  if (input === null || typeof input !== 'object') {
    throw new TypeError('createFormat: entrada deve ser um objeto');
  }
  return {
    formatId: String(input.formatId || input.id || ''),
    url: String(input.url || ''),
    container: String(input.container || input.ext || ''),
    codecs: String(input.codecs || ''),
    qualityLabel: String(input.qualityLabel || input.resolution || ''),
    bitrate: Number(input.bitrate || input.bandwidth || 0) || 0,
    width: Number(input.width) || 0,
    height: Number(input.height) || 0,
    fps: Number(input.fps) || 0,
    hasVideo: Boolean(input.hasVideo ?? (input.vcodec && input.vcodec !== 'none')),
    hasAudio: Boolean(input.hasAudio ?? (input.acodec && input.acodec !== 'none')),
    contentLength: Number(input.contentLength || input.filesize || input.estimatedSize || 0) || 0,
    language: String(input.language || ''),
    label: String(input.label || ''),
    isDefault: Boolean(input.isDefault),
    isAutoGenerated: Boolean(input.isAutoGenerated),
  };
}

/** Valida o shape de um Format ja normalizado (ou parcial). */
export function isValidFormat(format) {
  return (
    format !== null &&
    typeof format === 'object' &&
    typeof format.formatId === 'string' &&
    typeof format.url === 'string' &&
    typeof format.bitrate === 'number' &&
    typeof format.hasVideo === 'boolean' &&
    typeof format.hasAudio === 'boolean'
  );
}
