// ---------------------------------------------------------------------------
// P12: AudioTrack + SubtitleTrack models.
// ---------------------------------------------------------------------------

/**
 * Cria um AudioTrack normalizado — representa uma faixa de audio distinta
 * (idioma + qualidade). Uma faixa pode ter multiplos formatos.
 *
 * @param {object} [input]
 * @param {string} [input.language] — ISO 639-1 code (e.g. 'pt', 'en', 'und')
 * @param {string} [input.label] — human-readable name (e.g. 'Portuguese')
 * @param {boolean} [input.isDefault] — default track for this language
 * @param {Array<object>} [input.formats] — Format[] sorted by bitrate desc
 * @returns {{ language: string, label: string, isDefault: boolean, formats: Array }}
 */
export function createAudioTrack(input = {}) {
  return {
    language: String(input.language || 'und'),
    label: String(input.label || ''),
    isDefault: Boolean(input.isDefault),
    formats: Array.isArray(input.formats) ? input.formats : [],
  };
}

/**
 * Cria um SubtitleTrack normalizado — representa uma pista de legenda.
 *
 * @param {object} [input]
 * @param {string} [input.language] — ISO 639-1 code
 * @param {string} [input.label] — human-readable name
 * @param {boolean} [input.isAutoGenerated] — ASR auto-generated
 * @param {boolean} [input.isDefault] — default subtitle track
 * @param {object} [input.format] — { ext: 'vtt', url: '...' }
 * @returns {{ language: string, label: string, isAutoGenerated: boolean, isDefault: boolean, format: object|null }}
 */
export function createSubtitleTrack(input = {}) {
  return {
    language: String(input.language || 'und'),
    label: String(input.label || ''),
    isAutoGenerated: Boolean(input.isAutoGenerated),
    isDefault: Boolean(input.isDefault),
    format: input.format || null,
  };
}
